# Generated by Django 5.0.4 on 2024-04-26 12:23

import bet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_remove_option_author_bet_signup_code_bet_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='signup_code',
            field=models.CharField(default=bet.models.generate_random_code, editable=False, max_length=5, unique=True),
        ),
    ]
